---
title: "whale microorganism"
author: "Shiri"
date: "9/13/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(lme4)
library(tidyverse)
library(effects)
bigSmall=read.csv("word length in big and small OSF.csv")%>%
  mutate(correctedLength=length-phonemeRepW2letters)
```
Main analysis
```{r echo=FALSE}
comparison=lmer(correctedLength~meaning+(1|language)+(1|familyGeneral)+(1|familyGeneral:familySpecific)+(1|Macroarea),data=bigSmall)
summary(comparison)
```
Figure 2
```{r  echo=FALSE, messages=FALSE, warnings=FALSE}
library(ggrepel)
#the seed makes sure the labels and points go together
bigSmall%>%
  group_by(familyGeneral,meaning)%>%
  summarise(aveLength=mean(correctedLength))%>%
  ggplot(aes(meaning,aveLength,col=meaning,label=familyGeneral))+geom_violin()+
  geom_jitter(position=position_jitter(seed = 1))+
  ylab("Word Length")+xlab("Meaning")+theme_bw()+geom_text(size=2,position=position_jitter(seed = 1))

```

```{r echo=FALSE}
bigSmallAuto=bigSmall%>%
  mutate(autoLength=str_length(word)-phonemeRepW2letters)%>%
  mutate(vowelLength=str_count(word,"[aeouiE3]"))%>%
  mutate(consonantLength=autoLength-vowelLength)
```
only vowels
```{r echo=FALSE}
comparisonVowels=lmer(vowelLength~meaning+(1 + meaning|familyGeneral)+(1|familyGeneral:familySpecific)+(1|Macroarea),data=bigSmallAuto)
summary(comparisonVowels)
```

only consonants
```{r echo=FALSE}
comparisonConsonants=lmer(consonantLength~meaning+(1+meaning|familyGeneral)+(1|familyGeneral:familySpecific)+(1|Macroarea),data=bigSmallAuto)
summary(comparisonConsonants)
```
Figure 3
```{r echo=FALSE}
bigSmallAuto%>%
  group_by(familyGeneral,meaning)%>%
  summarise(aveVowel=mean(vowelLength),aveCons=mean(consonantLength))%>%
  ggplot(aes(aveCons,aveVowel,col=meaning))+geom_jitter(alpha=0.5)+theme_bw()+
  ylab("No, of vowels")+xlab("No. of consonants")
```

## Drawing the location of the languages in the sample
```{r echo=FALSE, message=FALSE, warnings=FALSE}
# library(maps)
# coordinates=read.csv("coordinates.csv")
# world=map_data("world")
```

```{r echo=FALSE, messages=FALSE, warnings=FALSE}
# coordinatesTypology=coordinates%>%
#   mutate(Longitude=as.numeric(Longitude))%>%
#   mutate(Latitude=as.numeric(Latitude))%>%
#   inner_join(bigSmall,by="Glottocode")
# ggplot()+geom_map(data=world,map=world,aes(long,lat,map_id=region))+
#   geom_point(data=coordinatesTypology,aes(Longitude,Latitude),color="green",size=0.9,alpha=0.7)+theme_bw()

```




